name: CI

on:
  push:
    branches:
      - '**'

  pull_request:
    branches:
      - '**'

jobs:
  androidBuild:
    defaults:
      run:
        working-directory: ./src/android

    name: Android build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: 'true'

      - name: Set up JDK 1.11
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Install Scons
        run: |
          sudo apt-get -q -y update
          sudo apt-get -q -y install scons

      - name: Assemble app debug APK
        run: ./gradlew assembleDebug

