name: CI

on: [push, pull_request]

jobs:
  androidBuild:
    defaults:
      run:
        working-directory: ./src/android

    name: Android build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: 'true'

      - name: Set up JDK 18
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '18'
          cache: gradle

      - name: Install Scons
        run: |
          sudo apt-get -q -y update
          sudo apt-get -q -y install scons

      - name: Assemble app debug APK
        run: ./gradlew assembleDebug check --no-daemon

      - name: Upload app APKs
        uses: actions/upload-artifact@v3
        with:
          name: app-debug
          path: |
            src/android/RHVoice-core/build/outputs/apk/stable/debug/RHVoice-core-stable-debug.apk
            src/android/RHVoice-core/build/outputs/apk/alpha/debug/RHVoice-core-alpha-debug.apk
            src/android/RHVoice-core/build/outputs/apk/dev/debug/RHVoice-core-dev-debug.apk

      - name: Upload Lint reports
        uses: actions/upload-artifact@v3
        with:
          name: app-lint
          path: src/android/RHVoice-core/build/reports/*
